name: Build webR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_dragonegg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure webR for dragonegg
        run: ./configure --with-dragonegg
      - name: Build webR with dragonegg
        run: make docker-webr
