name: Build webR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_dragonegg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure webR for dragonegg
        run: ./configure --with-dragonegg
      - name: Create webR docker container
        run: make docker-container-build
      - name: Build webR with dragonegg
        run: >
          docker exec build bash -c
          "source /webr-tools/emsdk/emsdk_env.sh && cd /app && make webr"
      - name: Run webR tests
        run: >
          docker exec build bash -c
          "source /webr-tools/emsdk/emsdk_env.sh && cd /app && make check"
